apiVersion: v1
kind: ServiceAccount
metadata:
  name: omnifeed-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend
    app.kubernetes.io/part-of: omnifeed
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gcpServiceAccount | quote }}
automountServiceAccountToken: false
