apiVersion: v1
kind: ServiceAccount
metadata:
  name: omnifeed-worker-summarizer
  namespace: {{ .Release.Namespace }}
  labels:
    app: worker-summarizer
    app.kubernetes.io/part-of: omnifeed
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gcpServiceAccount | quote }}
automountServiceAccountToken: true
