apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runner-set
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - repoURL: https://actions-runner-controller.github.io/actions-runner-controller
      chart: gha-runner-scale-set
      targetRevision: "0.12.x"
      helm:
        releaseName: omnifeed-runner-set
        valueFiles:
          - $values/helm/platform/arc/runner-set-values-dev.yaml
    - repoURL: https://github.com/your-org/news-feed-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
