apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform

  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: "33.x"
      helm:
        releaseName: traefik
        valueFiles:
          - $values/helm/platform/traefik/values-dev.yaml
    - repoURL: https://github.com/mb-news-summary/news-feed-infra.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
